export type SiniesterModel = {
    id: string,
    dni: string,
    full_name?: string,
    age?: number,
    sex?: string,
    date: { _seconds: number, _nanoseconds: number },
    hour: string,
    attack_type: string,
    geopoint: {
        lat: number,
        lng: number
    },
    location?: string,
    place_description?: string,
    thief_age?: string,
    thief_hair_color?: string,
    thief_height?: string,
    thief_skin?: string,
    thief_clothing?: string,
    thief_accompanied?: number,
    thief_armed?: boolean,
    thief_physical?: string,
    victim_accompaniment?: string,
    thief_sex?: string,
    thief_description?: string,
    thief_company?: number,
    victim_company?: string,
    physical_damage: number,
    emotional_damage: number,
    thief_agressiveness: number,
    stolen_items?: string[],
    other_items?: string,
    comment?: string,
    severity: number,
    time: number,
    hash: string,
    createdAt: number,
    state: 'Pendiente' | 'En revision' | 'Revisado',
    suspects: string[],
    versions: {
        [date: string]: SiniesterModel
    }
}